### ISSUE TITLE
Problem with Jupyter

### ISSUE THREAD

**Issue by cgarciae** [gettyimages/docker-spark#11]
I've tried to install Jupyter on top of your setup like this: 

```
# spark.dockerfile
FROM gettyimages/spark

RUN apt-get -y update
RUN apt-get -y install python-dev python-pip python-numpy 
RUN apt-get -y install python-scipy python-pandas gfortran 
RUN apt-get -y install ipython ipython-notebook

RUN pip3 install --upgrade pip 
RUN pip3 install jupyter 
```

and then created a container in docker-compose to run jupyter 

```
jupyter:
    build:
      context: .
      dockerfile: spark.dockerfile
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - 8888:8888
    environment:
      PYSPARK_DRIVER_PYTHON: ipython 
      PYSPARK_DRIVER_PYTHON_OPTS: 'notebook --ip=0.0.0.0 --no-browser --debug'
    command: jupyter notebook --ip=0.0.0.0 --no-browser --debug
```

However the Kernel is never able to start and I get messages like these: 

> Connecting to: tcp://127.0.0.1:43250
> jupyter_1  | [I 17:48:34.044 NotebookApp] KernelRestarter: restarting kernel (1/5)
> jupyter_1  | [D 17:48:34.045 NotebookApp] Starting kernel: ['/usr/bin/python3', '-m', 'ipykernel', '-f', >'/root/.local/share/jupyter/runtime/kernel-4579c251-9
> bb9-4d3f-ae26-6d5f75a175a5.json']
> jupyter_1  | [D 17:48:34.047 NotebookApp] Connecting to: tcp://127.0.0.1:58451
> jupyter_1  | [I 17:48:37.050 NotebookApp] KernelRestarter: restarting kernel (2/5)
> jupyter_1  | [D 17:48:37.050 NotebookApp] Starting kernel: ['/usr/bin/python3', '-m', 'ipykernel', '-f', >'/root/.local/share/jupyter/runtime/kernel-4579c251-9
> bb9-4d3f-ae26-6d5f75a175a5.json']
> jupyter_1  | [D 17:48:37.052 NotebookApp] Connecting to: tcp://127.0.0.1:58451
> jupyter_1  | [I 17:48:40.054 NotebookApp] KernelRestarter: restarting kernel (3/5)

Any idea why? Using this other command doesn't help either

```
/usr/spark-2.0.0/bin/pyspark --master spark://master:7077
```

Notice that `PYSPARK_DRIVER_PYTHON` and `PYSPARK_DRIVER_PYTHON_OPTS` are already set in the docker compose file.
