### ISSUE TITLE
Deploying Spark on a Swarm Cluster

### ISSUE THREAD

**Issue by hamzehkhazaei** [gettyimages/docker-spark#22]
Hello there,
I am using your image to create a cluster of Spark on a Swarm cluster. here is what I do:
`$ docker network create --driver overlay spark`
`$ docker service create --name master --network spark --constraint 'node.labels.name==manager-node' -p 7077:7077 -p 8080:8080 gettyimages/spark:2.1.0-hadoop-2.7 bin/spark-class org.apache.spark.deploy.master.Master`
`$ docker service create --name worker --network spark --constraint 'node.labels.name==worker-node' -p 8081:8080 gettyimages/spark:2.1.0-hadoop-2.7 bin/spark-class org.apache.spark.deploy.worker.Worker spark://10.7.1.3:7077`
in which `10.7.1.3` is the ip address that I see in the Spark master webUI.
However, the Spark worker doesn't show up in the master webUI. The port 7077 is open on the Swarm manager node. But if I deploy the Spark worker and master on the same node, Spark master can see the worker. I am using the latest version of Docker. I am not sure if your image has been built for such a scenario? Any hint what might be the reason for this?

Thanks,
Henaras

**Comment by bizarte** [comment]
It seems you need to publish your 8081:8081 for your worker. It basically means binding the container's 8081 port with the local host's 8081. Thus when you browser localhost:8080/8081, the page will show up as local page on any node machine of your swarm.

**Comment by Danny4927** [comment]
Hey I am also trying to deploy spark in a swarm cluster, but if i try to start the master service it is stuck:
`$ docker service ps master`


NAME  |  IMAGE                        |       NODE | DESIRED STATE | CURRENT STATE      |     ERROR | PORTS
------------ | ------------- | ------------- | ------------- | ------------- | ------------- | -------------
master.1  |  gettyimages/spark:2.1.0-hadoop-2.7   |  |   Running     |   Pending 16 minutes ago |  |  


It always says it is pending. My swarm consists of 2 VMs and i also tried it with nginx, which was working fine. Did you do anything special? How long does it take untill the master is running?

UPDATE: It was a problem with the constraint, now i have the same issues as @henaras. I also tried to use `-p 8081:8081` as recommended by @bizarte. Has anyone a working soltution for a docker swarm?

**Comment by laugimethods** [comment]
Hi,

We do successfully run a Spark Cluster on Docker Swarm:
https://github.com/Logimethods/smart-meter

Btw, this work is still in progress. In particular, we plan to get rid of some Python hacks by enforcing embedded dependencies between containers: https://github.com/Logimethods/docker-eureka

Regards.

**Comment by Danny4927** [comment]
Hi, 
thanks for your answer. It is working now. It was a problem with Virtual Box. Had to allow promiscous mode an then it worked. I forked it under: [https://github.com/Danny4927/docker-spark](https://github.com/Danny4927/docker-spark) to run a simple SparkPi

**Comment by hamzehkhazaei** [comment]
Thanks @bizarte , that is a typo, I meant 8081:8081 as you pointed out.
Thanks @laugimethods ; but I guess yours is working because you deploy both master and workers on the same virtual machine? also, you do not publish any port for the Spark master and slave services. I found some threads here and there stating that *docker* has some problems with overlay networks when publishing ports on them.

**Comment by brunowego** [comment]
The code below works for me. 🥇 

```yml
version: '3.6'

x-proxy: &proxy
  http_proxy: ${http_proxy}
  https_proxy: ${https_proxy}
  no_proxy: ${no_proxy}

services:
  spark-master:
    image: gettyimages/spark:2.3.1-hadoop-3.0
    hostname: spark-master
    volumes:
      - type: volume
        source: sm-data
        target: /tmp/data
    configs:
      - source: sm-config
        target: /conf/spark-defaults.conf
    env_file: ./services/spark/.env
    environment:
      <<: *proxy
      MASTER: spark://spark-master:7077
    command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7077
      - 6066
    ports:
      - target: 4040
        published: 4040
        protocol: tcp
      - target: 6066
        published: 6066
        protocol: tcp
      - target: 7077
        published: 7077
        protocol: tcp
      - target: 8080
        published: 8080
        protocol: tcp
    networks:
      - workshop
    restart: always
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == manager

  spark-worker:
    image: gettyimages/spark:2.3.1-hadoop-3.0
    hostname: spark-worker
    volumes:
      - type: volume
        source: sw-data
        target: /tmp/data
    configs:
      - source: sw-config
        target: /conf/spark-defaults.conf
    env_file: ./services/spark/.env
    environment:
      <<: *proxy
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 8881
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
    networks:
      - workshop
    restart: always
    depends_on:
      - spark-master
    deploy:
      replicas: 4
      placement:
        constraints:
          - node.role == manager

volumes:
  sm-data:
    driver: local
  sw-data:
    driver: local

configs:
  sm-config:
    file: ./services/spark/conf/master/spark-defaults.conf
  sw-config:
    file: ./services/spark/conf/worker/spark-defaults.conf

networks:
  workshop:
    name: workshop
    external: true
```

Pay attention with `spark-master` service name, I tried use with underscore but I get issues.
